stages:
  - test
  - build
  - docker

variables:
  DOCKER_TAG: "registry.gitlab.com/sirber/tiny-crm/tiny-crm:latest"

test:
  image: node:20-alpine
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - apk add --no-cache make go
  script: 
    - make test

build:
  image: node:20-alpine
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache make go
  script:
    - make build
  artifacts:
    paths:
      - ./dist/*

docker:
  image: docker:latest
  services:
    - docker:dind
  stage: docker
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$DOCKER_TAG" .
    - docker push "$DOCKER_TAG"