name: tiny-crm

services:
  app:
    container_name: tiny-crm-dev-app
    build:
      context: .
      dockerfile: resources/docker/Dockerfile.dev
    restart: on-failure:5
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tiny-crm
      - NODE_ENV=development
    volumes:
      - ./:/app:z

  mongodb:
    container_name: tiny-crm-dev-mongodb
    image: mongo:8.0-noble
    restart: on-failure:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=crm
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    command: ["--auth"]

volumes:
  mongodb_data: