name: tiny-crm

services:
  app:
    container_name: tiny-crm-dev-app
    image: node:22-slim
    restart: no
    working_dir: /app
    command: npm run dev
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:crm@db:5432/tiny-crm?connection_limit=10
      - NODE_ENV=development
    volumes:
      - ./:/app

  db:
    container_name: tiny-crm-dev-db
    image: postgres:17-alpine
    restart: no
    environment:
    - POSTGRES_PASSWORD=crm
    ports:
    - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: