services:
  app:
    container_name: tiny-crm-dev-app
    image: node:22-alpine
    restart: unless-stopped
    working_dir: /app
    command: yarn dev
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:crm@db:5432/tiny-crm?connection_limit=10
      - NODE_ENV=development
    volumes:
      - ./:/app
      - next:/app/.next

  db:
    container_name: tiny-crm-dev-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
    - POSTGRES_PASSWORD=crm
    ports:
    - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  next: 