services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:crm@db:3306/tiny-crm
      - NODE_ENV=production

  db:
    restart: unless-stopped
    image: mysql:8
    environment:
    - MYSQL_ROOT_PASSWORD=crm
    ports:
    - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: