services:
  app:
    image: node:22-alpine
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:crm@db:3306/tiny-crm
      - NODE_ENV=development
    volumes:
      - ./:/app

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
    - MYSQL_ROOT_PASSWORD=crm
    ports:
    - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: