services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./database:/app/prisma/database
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
