# ./resources/docker/Dockerfile.dev
FROM node:22-slim

# Install dependencies needed by Prisma
RUN apt-get update && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Start the app using npm script
CMD ["npm", "run", "dev"]
