name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker images
      run: |
        docker build --target runner -t ghcr.io/${{ github.repository }}/tiny-crm:latest . 
        docker build --target migrate -t ghcr.io/${{ github.repository }}/tiny-crm-migrate:latest .
        
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/tiny-crm:latest
        docker push ghcr.io/${{ github.repository }}/tiny-crm-migrate:latest
